var mongoose = require("../db");
var Schema = mongoose.Schema;

var ResultSchema = new Schema(
  {
    position: { type: Number, required: true },
    horseName: { type: String, required: true },
    horseId: { type: Schema.Types.ObjectId, ref: "Horse", default: null },
    participantId: { type: Schema.Types.ObjectId },
    jockeyId: { type: Schema.Types.ObjectId, ref: "User" },
    jockeyName: { type: String },
    time: { type: String },
    points: { type: Number, default: 0 },
    notes: { type: String },
    status: {
      type: String,
      enum: ["FINISHED", "DISQUALIFIED"],
      default: undefined,
    },
    source: { type: String, enum: ["MANUAL", "SIMULATION"], default: "MANUAL" },
    simulationRunId: { type: String, default: null },
  },
  { _id: true },
);

var SimulationCheckpointSchema = new Schema(
  {
    at: { type: Number, required: true },
    progress: { type: Number, required: true },
  },
  { _id: false },
);

var SimulationParticipantSchema = new Schema(
  {
    participantId: { type: Schema.Types.ObjectId, required: true },
    horseId: { type: Schema.Types.ObjectId, ref: "Horse", required: true },
    horseName: { type: String, required: true },
    jockeyId: { type: Schema.Types.ObjectId, ref: "User", default: null },
    jockeyName: { type: String, default: "" },
    gateNumber: { type: Number, required: true },
    horseStarts: { type: Number, default: 0 },
    horseWins: { type: Number, default: 0 },
    horseWinRate: { type: Number, default: 0.5 },
    jockeyStarts: { type: Number, default: 0 },
    jockeyWins: { type: Number, default: 0 },
    jockeyWinRate: { type: Number, default: 0.5 },
    initialWinProbability: { type: Number, default: 0 },
    luckValue: { type: Number, default: 0 },
    rank: { type: Number, required: true },
    finishTimeMillis: { type: Number, required: true },
    checkpoints: { type: [SimulationCheckpointSchema], default: [] },
  },
  { _id: false },
);

var RaceSimulationSchema = new Schema(
  {
    status: {
      type: String,
      enum: ["NOT_STARTED", "GENERATED", "CONFIRMING", "CONFIRMED"],
      default: "NOT_STARTED",
    },
    runId: { type: String, default: null },
    algorithmVersion: { type: String, default: "v1" },
    seed: { type: String, default: null },
    historyWeight: { type: Number, default: 0.5 },
    luckWeight: { type: Number, default: 0.5 },
    generatedAt: { type: Date, default: null },
    generatedBy: { type: Schema.Types.ObjectId, ref: "User", default: null },
    playbackDurationMs: { type: Number, default: 28000 },
    playbackEndsAt: { type: Date, default: null },
    confirmedAt: { type: Date, default: null },
    confirmedBy: { type: Schema.Types.ObjectId, ref: "User", default: null },
    participants: { type: [SimulationParticipantSchema], default: [] },
  },
  { _id: false },
);

var RaceSchema = new Schema(
  {
    raceNumber: { type: Number, required: true },
    name: { type: String, required: true },
    distance: { type: String, required: true },
    scheduledAt: { type: Date },
    scheduledEndAt: { type: Date },
    venueId: { type: String, default: "" },
    venueName: { type: String, default: "" },
    venueAddress: { type: String, default: "" },
    status: {
      type: String,
      enum: [
        "Nháp",
        "Đã công bố",
        "Đang mở đăng ký",
        "Đã đóng đăng ký",
        "Sắp chạy",
        "Sắp diễn ra",
        "Đang chạy",
        "Đang diễn ra",
        "Hoàn thành",
        "Đã hủy",
      ],
      default: "Nháp",
    },
    description: { type: String },
    track: { type: String, default: "" },
    surface: { type: String, default: "Cỏ" },
    category: { type: String, default: "Open" },
    minHorses: { type: Number, default: 0 },
    maxHorses: { type: Number, default: 0 },
    entryFee: { type: Number, default: 0 },
    deposit: { type: Number, default: 0 },
    regDeadline: { type: Date },
    checkIn: { type: String, default: "" },
    prizes: { type: Schema.Types.Mixed, default: [] },
    results: [ResultSchema],
    refereeId: { type: Schema.Types.ObjectId, ref: "User" },
    salaryConfigId: { type: Schema.Types.ObjectId, ref: "RefereeSalaryConfig" },
    refereePaymentStatus: {
      type: String,
      enum: ["NONE", "HELD", "PAID", "RELEASED"],
      default: "NONE",
    },
    refereePaymentAmount: { type: Number, default: 0 },
    financialSettlementStatus: {
      type: String,
      enum: ["NONE", "SETTLING", "SETTLED", "CANCELLED"],
      default: "NONE",
    },
    financialSettledAt: { type: Date, default: null },
    financialSettlementSnapshot: { type: Schema.Types.Mixed, default: null },
    resultFinalizedAt: { type: Date, default: null },
    resultFinalizedBy: { type: Schema.Types.ObjectId, ref: "User", default: null },
    simulation: { type: RaceSimulationSchema, default: function () { return {}; } },
  },
  { _id: true },
);

var RegistrationSchema = new Schema(
  {
    tournamentId: { type: Schema.Types.ObjectId, ref: "Tournament" },
    fullName: { type: String, required: true },
    ownerId: { type: Schema.Types.ObjectId, ref: "User" },
    ownerName: { type: String },
    horseId: { type: Schema.Types.ObjectId, ref: "Horse" },
    horseName: { type: String, required: true },
    horseAge: { type: Number },
    horseBreed: { type: String },
    jockeyId: { type: Schema.Types.ObjectId, ref: "User" },
    jockeyName: { type: String },
    jockeyInvitationId: { type: Schema.Types.ObjectId, ref: "JockeyInvitation" },
    raceId: { type: Schema.Types.ObjectId },
    status: {
      type: String,
      enum: ["Chờ duyệt", "Đã duyệt", "Từ chối", "Đã rút", "Đang chạy", "Hoàn thành"],
      default: "Chờ duyệt",
    },
    gateNumber: { type: Number },
    checkInStatus: {
      type: String,
      enum: ["PENDING", "CHECKED_IN", "ABSENT"],
      default: "PENDING",
    },
    participantStatus: {
      type: String,
      enum: ["REGISTERED", "CHECKED_IN", "RACING", "FINISHED", "DISQUALIFIED", "ABSENT"],
      default: "REGISTERED",
    },
    notes: { type: String },
    reviewNote: { type: String },
    withdrawNote: { type: String },
    reviewedBy: { type: Schema.Types.ObjectId, ref: "User" },
    reviewedAt: { type: Date },
    entryFeeAmount: { type: Number, default: 0 },
    depositAmount: { type: Number, default: 0 },
    paymentStatus: {
      type: String,
      enum: ["UNCHARGED", "CHARGED", "REFUNDED", "FORFEITED", "LEGACY_NO_CHARGE"],
      default: "UNCHARGED",
    },
    depositStatus: {
      type: String,
      enum: ["NONE", "HELD", "REFUNDED", "FORFEITED"],
      default: "NONE",
    },
    paymentOperationId: { type: Schema.Types.ObjectId, ref: "WalletOperation", default: null },
    depositOperationId: { type: Schema.Types.ObjectId, ref: "WalletOperation", default: null },
    registeredAt: { type: Date, default: Date.now },
  },
  { _id: true },
);

var TournamentSchema = new Schema(
  {
    name: { type: String, required: true },
    slug: { type: String, required: true, unique: true, index: true },
    description: { type: String, default: "" },
    location: { type: String, required: true },
    banner: { type: String, default: "" },
    type: {
      type: String,
      enum: ["regular", "championship"],
      default: "regular",
    },
    status: {
      type: String,
      enum: [
        "Nháp",
        "Đã công bố",
        "Đang mở đăng ký",
        "Đã đóng đăng ký",
        "Đã lên lịch",
        "Đang diễn ra",
        "Đã kết thúc",
        "Đã hủy",
      ],
      default: "Nháp",
    },
    startDate: { type: Date },
    endDate: { type: Date },
    provinceId: { type: Schema.Types.ObjectId, ref: "Province" },
    registrationOpenAt: { type: Date },
    checkInDeadlineAt: { type: Date },
    minTeams: { type: Number, default: 1 },
    maxTeams: { type: Number, default: 0 },
    minHorsesPerOwner: { type: Number, default: 4 },
    maxHorsesPerOwner: { type: Number, default: 10 },
    jockeyChallengeEnabled: { type: Boolean, default: false },
    jockeyChallengeFirstPoints: { type: Number, default: 3 },
    jockeyChallengeSecondPoints: { type: Number, default: 2 },
    jockeyChallengeThirdPoints: { type: Number, default: 1 },
    jockeyChallengePrizes: {
      type: [
        {
          rank: { type: Number, required: true },
          amount: { type: Number, default: 0 },
          note: { type: String, default: "" },
        },
      ],
      default: [],
    },
    rules: { type: String, default: "" },
    config: {
      entryFee: { type: Number, default: 0 },
      depositFee: { type: Number, default: 0 },
      refundDays: { type: Number, default: 3 },
      maxRaces: { type: Number, default: 0 },
      maxRegistrations: { type: Number, default: 0 },
      requireJockey: { type: Boolean, default: true },
      requireHorseOwner: { type: Boolean, default: true },
      requireVetCheck: { type: Boolean, default: true },
      requireDopingCheck: { type: Boolean, default: true },
      allowLateRegistration: { type: Boolean, default: false },
      deadlineAt: { type: Date },
    },
    races: [RaceSchema],
    registrations: [RegistrationSchema],
    createdBy: { type: Schema.Types.ObjectId, ref: "User" },
  },
  { timestamps: true },
);

module.exports = mongoose.model("Tournament", TournamentSchema);
